_target_: gaze_model.GazePredictor
feature_extractor:
  feature_extractor_repo: 'facebookresearch/dinov2'
  feature_extractor_name: 'dinov2_vitl14_reg'  # DINOv2 model name
  feature_dim: 768  # Dimension of the features extracted by DINOv2
  hidden_dims: [512, 256, 128]  # Hidden dimensions for the MLP
  output_dim: 1  # Output dimension for gaze prediction
  hidden_activation: 'relu'  # Activation function for the MLP
  output_activation: 'sigmoid'  # Activation for the final output layer