defaults:
  - models@model: gaze_pre
  - dataset@dataset: gaze_dataset
wandb:
  project: test        # replace with your project name
  entity: ahmad-baki-karlsruhe-institute-of-technology # replace with your WandB entity (team/user)

epochs: 1                # default number of epochs
loss_function: ce        # loss function to use: mse, ce
optimizer: adam          # optimizer to use: adam, sgd
dropout: 1
learning_rate: 0.001
batch_size: 32
